name: Multi-Job Python CI

on: [push, pull_request]

jobs:
  lint:
    name: Run Linter (flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .

  format:
    name: Check Code Format (black)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install black
        run: pip install black

      - name: Run black check
        run: black --check .

    name: Run Unit Tests (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        run: pytest -v

    - name: Show current directory
      run: pwd

    - name: List all files
      run: ls -R


Run Unit Tests (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        run: pytest -v

    - name: Show current directory
      run: pwd

    - name: List all files
      run: ls -R


